#**Product Matching**
***
**Problem statement:**

Using ML/DL techniques, match similar products from the Flipkart dataset with the Amazon dataset. Once
similar products are matched, display the retail price from FK and AMZ side by side.

**Dataset**

Link: https://www.dropbox.com/sh/aypq6h3254207bs/AACzMLvo-XtK9sYAAma6FW0la?dl=0

##Importing Libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

##Getting Data

### Amazon Data

In [ ]:
df_amz = pd.read_csv('/content/drive/MyDrive/data/Shack_Labs_Assignment/DS - Assignment Part 2 data set/amz_com-ecommerce_sample.csv',engine='python',encoding='latin1')
df_amz.head().T

,0,1,2,3,4
uniq_id,c2d766ca982eca8304150849735ffef9,7f7036a6d550aaa89d34c77bd39a5e48,f449ec65dcbc041b6ae5e6a32717d01b,0973b37acd0c664e3de26e97e5571454,bc940ea42ee6bef5ac7cea3fb5cfbee7
crawl_timestamp,2016-03-25 22:59:23 +0000,2016-03-25 22:59:23 +0000,2016-03-25 22:59:23 +0000,2016-03-25 22:59:23 +0000,2016-03-25 22:59:23 +0000
product_url,http://www.flipkart.com/alisha-solid-women-s-c...,http://www.flipkart.com/fabhomedecor-fabric-do...,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,http://www.flipkart.com/alisha-solid-women-s-c...,http://www.flipkart.com/sicons-all-purpose-arn...
product_name,Alisha Solid Women's Cycling Shorts,FabHomeDecor Fabric Double Sofa Bed,AW Bellies,Alisha Solid Women's Cycling Shorts,Sicons All Purpose Arnica Dog Shampoo
product_category_tree,"[""Clothing >> Women's Clothing >> Lingerie, Sl...","[""Furniture >> Living Room Furniture >> Sofa B...","[""Footwear >> Women's Footwear >> Ballerinas >...","[""Clothing >> Women's Clothing >> Lingerie, Sl...","[""Pet Supplies >> Grooming >> Skin & Coat Care..."
pid,SRTEH2FF9KEDEFGF,SBEEH3QGU7MFYJFY,SHOEH4GRSUBJGZXE,SRTEH2F6HUZMQ6SJ,PSOEH3ZYDMSYARJ5
retail_price,982,32143,991,694,208
discounted_price,438,29121,551,325,258
image,"[""http://img5a.flixcart.com/image/short/u/4/a/...","[""http://img6a.flixcart.com/image/sofa-bed/j/f...","[""http://img5a.flixcart.com/image/shoe/7/z/z/r...","[""http://img5a.flixcart.com/image/short/6/2/h/...","[""http://img5a.flixcart.com/image/pet-shampoo/..."
is_FK_Advantage_product,False,False,False,False,False
description,Key Features of Alisha Solid Women's Cycling S...,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,Key Features of AW Bellies Sandals Wedges Heel...,Key Features of Alisha Solid Women's Cycling S...,Specifications of Sicons All Purpose Arnica Do...
product_rating,No rating available,No rating available,No rating available,No rating available,No rating available
overall_rating,No rating available,No rating available,No rating available,No rating available,No rating available
brand,Alisha,FabHomeDecor,AW,Alisha,Sicons
product_specifications,"{""product_specification""=>[{""key""=>""Number of ...","{""product_specification""=>[{""key""=>""Installati...","{""product_specification""=>[{""key""=>""Ideal For""...","{""product_specification""=>[{""key""=>""Number of ...","{""product_specification""=>[{""key""=>""Pet Type"",..."

In [ ]:
df_amz.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   uniq_id                  20000 non-null  object
 1   crawl_timestamp          20000 non-null  object
 2   product_url              20000 non-null  object
 3   product_name             20000 non-null  object
 4   product_category_tree    20000 non-null  object
 5   pid                      20000 non-null  object
 6   retail_price             20000 non-null  int64
 7   discounted_price         20000 non-null  int64
 8   image                    19997 non-null  object
 9   is_FK_Advantage_product  20000 non-null  bool
 10  description              19998 non-null  object
 11  product_rating           20000 non-null  object
 12  overall_rating           20000 non-null  object
 13  brand                    14136 non-null  object
 14  product_specifications   19986 non-null  object
dtypes: bool(1), int64(2), object(12)
memory usage: 2.2+ MB

In [ ]:
#checking for missing values
df_amz.isna().sum()/len(df_amz)*100

uniq_id                     0.000
crawl_timestamp             0.000
product_url                 0.000
product_name                0.000
product_category_tree       0.000
pid                         0.000
retail_price                0.000
discounted_price            0.000
image                       0.015
is_FK_Advantage_product     0.000
description                 0.010
product_rating              0.000
overall_rating              0.000
brand                      29.320
product_specifications      0.070
dtype: float64

Observations
* Not much missing values
* Brand have almost 30 percent missing values

In [ ]:
df_amz.describe().T

,count,mean,std,min,25%,50%,75%,max
retail_price,20000.0,2957.09515,8993.993257,-20.0,647.0,999.0,1986.0,571223.0
discounted_price,20000.0,2364.59705,8994.623680,0.0,424.0,663.0,1235.0,726879.0

In [ ]:
df_amz.describe(include='O').T

,count,unique,top,freq
uniq_id,20000,20000,c2d766ca982eca8304150849735ffef9,1
crawl_timestamp,20000,371,2015-12-01 12:40:44 +0000,1979
product_url,20000,20000,http://www.flipkart.com/alisha-solid-women-s-c...,1
product_name,20000,12734,THELOSTPUPPY BACK COVER FOR APPLE IPAD AIR,141
product_category_tree,20000,6466,"[""Jewellery >> Necklaces & Chains >> Necklaces""]",1567
pid,20000,19998,JEAEGE8Q8GXYFTGU,2
image,19997,18589,"[""http://img6a.flixcart.com/image/car-mat/m/t/...",45
description,19998,17540,TheLostPuppy Back Cover for Apple iPad Air (Mu...,92
product_rating,20000,36,No rating available,18151
overall_rating,20000,36,No rating available,18151
brand,14136,3499,Allure Auto,469
product_specifications,19986,18825,"{""product_specification""=>[{""key""=>""Type"", ""va...",71

Observations
*  Mean of retail price is approx 3000 where as of discounted price is approx 2400
*  Some products have retailed price in negative needs to check the data
*  Discounted price of few products are greater than their respective retail price
*  Most of the product belongs to ["Jewellery >> Necklaces & Chains >> Necklaces"] 	
*  Approx of 91 percent of the products doesn't have either of the rating, can drop both of them

### Flipkart Data

In [ ]:
df_fk = pd.read_csv('/content/drive/MyDrive/data/Shack_Labs_Assignment/DS - Assignment Part 2 data set/flipkart_com-ecommerce_sample.csv')
df_fk.head().T

,0,1,2,3,4
uniq_id,c2d766ca982eca8304150849735ffef9,7f7036a6d550aaa89d34c77bd39a5e48,f449ec65dcbc041b6ae5e6a32717d01b,0973b37acd0c664e3de26e97e5571454,bc940ea42ee6bef5ac7cea3fb5cfbee7
crawl_timestamp,2016-03-25 22:59:23 +0000,2016-03-25 22:59:23 +0000,2016-03-25 22:59:23 +0000,2016-03-25 22:59:23 +0000,2016-03-25 22:59:23 +0000
product_url,http://www.flipkart.com/alisha-solid-women-s-c...,http://www.flipkart.com/fabhomedecor-fabric-do...,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,http://www.flipkart.com/alisha-solid-women-s-c...,http://www.flipkart.com/sicons-all-purpose-arn...
product_name,Alisha Solid Women's Cycling Shorts,FabHomeDecor Fabric Double Sofa Bed,AW Bellies,Alisha Solid Women's Cycling Shorts,Sicons All Purpose Arnica Dog Shampoo
product_category_tree,"[""Clothing >> Women's Clothing >> Lingerie, Sl...","[""Furniture >> Living Room Furniture >> Sofa B...","[""Footwear >> Women's Footwear >> Ballerinas >...","[""Clothing >> Women's Clothing >> Lingerie, Sl...","[""Pet Supplies >> Grooming >> Skin & Coat Care..."
pid,SRTEH2FF9KEDEFGF,SBEEH3QGU7MFYJFY,SHOEH4GRSUBJGZXE,SRTEH2F6HUZMQ6SJ,PSOEH3ZYDMSYARJ5
retail_price,999.0,32157.0,999.0,699.0,220.0
discounted_price,379.0,22646.0,499.0,267.0,210.0
image,"[""http://img5a.flixcart.com/image/short/u/4/a/...","[""http://img6a.flixcart.com/image/sofa-bed/j/f...","[""http://img5a.flixcart.com/image/shoe/7/z/z/r...","[""http://img5a.flixcart.com/image/short/6/2/h/...","[""http://img5a.flixcart.com/image/pet-shampoo/..."
is_FK_Advantage_product,False,False,False,False,False
description,Key Features of Alisha Solid Women's Cycling S...,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,Key Features of AW Bellies Sandals Wedges Heel...,Key Features of Alisha Solid Women's Cycling S...,Specifications of Sicons All Purpose Arnica Do...
product_rating,No rating available,No rating available,No rating available,No rating available,No rating available
overall_rating,No rating available,No rating available,No rating available,No rating available,No rating available
brand,Alisha,FabHomeDecor,AW,Alisha,Sicons
product_specifications,"{""product_specification""=>[{""key""=>""Number of ...","{""product_specification""=>[{""key""=>""Installati...","{""product_specification""=>[{""key""=>""Ideal For""...","{""product_specification""=>[{""key""=>""Number of ...","{""product_specification""=>[{""key""=>""Pet Type"",..."

In [ ]:
df_fk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   uniq_id                  20000 non-null  object
 1   crawl_timestamp          20000 non-null  object
 2   product_url              20000 non-null  object
 3   product_name             20000 non-null  object
 4   product_category_tree    20000 non-null  object
 5   pid                      20000 non-null  object
 6   retail_price             19922 non-null  float64
 7   discounted_price         19922 non-null  float64
 8   image                    19997 non-null  object
 9   is_FK_Advantage_product  20000 non-null  bool
 10  description              19998 non-null  object
 11  product_rating           20000 non-null  object
 12  overall_rating           20000 non-null  object
 13  brand                    14136 non-null  object
 14  product_specifications   19986 non-null  object
dtypes: bool(1), float64(2), object(12)
memory usage: 2.2+ MB

In [ ]:
# checking for the missing values
df_fk.isna().sum()/len(df_fk)*100

uniq_id                     0.000
crawl_timestamp             0.000
product_url                 0.000
product_name                0.000
product_category_tree       0.000
pid                         0.000
retail_price                0.390
discounted_price            0.390
image                       0.015
is_FK_Advantage_product     0.000
description                 0.010
product_rating              0.000
overall_rating              0.000
brand                      29.320
product_specifications      0.070
dtype: float64

Observations
*  More missing values than amazon data
*  Brand has 30 percent missing values
*  Approx of 4 percent of the both retailed and discounted price are missing

In [ ]:
df_fk.describe().T

,count,mean,std,min,25%,50%,75%,max
retail_price,19922.0,2979.206104,9009.639341,35.0,666.0,1040.0,1999.0,571230.0
discounted_price,19922.0,1973.401767,7333.586040,35.0,350.0,550.0,999.0,571230.0

In [ ]:
df_fk.describe(include='O').T

,count,unique,top,freq
uniq_id,20000,20000,c2d766ca982eca8304150849735ffef9,1
crawl_timestamp,20000,371,2015-12-01 12:40:44 +0000,1979
product_url,20000,20000,http://www.flipkart.com/alisha-solid-women-s-c...,1
product_name,20000,12676,TheLostPuppy Back Cover for Apple iPad Air,134
product_category_tree,20000,6466,"[""Jewellery >> Necklaces & Chains >> Necklaces""]",1567
pid,20000,19998,JEAEGE8Q8GXYFTGU,2
image,19997,18589,"[""http://img6a.flixcart.com/image/car-mat/m/t/...",45
description,19998,17539,TheLostPuppy Back Cover for Apple iPad Air (Mu...,92
product_rating,20000,36,No rating available,18151
overall_rating,20000,36,No rating available,18151
brand,14136,3499,Allure Auto,469
product_specifications,19986,18825,"{""product_specification""=>[{""key""=>""Type"", ""va...",71

Observations
*  Mean of retail price is approx 3000 where as of discounted price is approx 2000
*  Most of the product belongs to ["Jewellery >> Necklaces & Chains >> Necklaces"] 	
*  Approx of 91 percent of the products doesn't have either of the rating, can drop both of them

**Combined Dataset**

In [ ]:
combined_data = pd.concat([df_fk,df_amz],axis=0)
combined_data.head().T

,0,1,2,3,4
uniq_id,c2d766ca982eca8304150849735ffef9,7f7036a6d550aaa89d34c77bd39a5e48,f449ec65dcbc041b6ae5e6a32717d01b,0973b37acd0c664e3de26e97e5571454,bc940ea42ee6bef5ac7cea3fb5cfbee7
crawl_timestamp,2016-03-25 22:59:23 +0000,2016-03-25 22:59:23 +0000,2016-03-25 22:59:23 +0000,2016-03-25 22:59:23 +0000,2016-03-25 22:59:23 +0000
product_url,http://www.flipkart.com/alisha-solid-women-s-c...,http://www.flipkart.com/fabhomedecor-fabric-do...,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,http://www.flipkart.com/alisha-solid-women-s-c...,http://www.flipkart.com/sicons-all-purpose-arn...
product_name,Alisha Solid Women's Cycling Shorts,FabHomeDecor Fabric Double Sofa Bed,AW Bellies,Alisha Solid Women's Cycling Shorts,Sicons All Purpose Arnica Dog Shampoo
product_category_tree,"[""Clothing >> Women's Clothing >> Lingerie, Sl...","[""Furniture >> Living Room Furniture >> Sofa B...","[""Footwear >> Women's Footwear >> Ballerinas >...","[""Clothing >> Women's Clothing >> Lingerie, Sl...","[""Pet Supplies >> Grooming >> Skin & Coat Care..."
pid,SRTEH2FF9KEDEFGF,SBEEH3QGU7MFYJFY,SHOEH4GRSUBJGZXE,SRTEH2F6HUZMQ6SJ,PSOEH3ZYDMSYARJ5
retail_price,999.0,32157.0,999.0,699.0,220.0
discounted_price,379.0,22646.0,499.0,267.0,210.0
image,"[""http://img5a.flixcart.com/image/short/u/4/a/...","[""http://img6a.flixcart.com/image/sofa-bed/j/f...","[""http://img5a.flixcart.com/image/shoe/7/z/z/r...","[""http://img5a.flixcart.com/image/short/6/2/h/...","[""http://img5a.flixcart.com/image/pet-shampoo/..."
is_FK_Advantage_product,False,False,False,False,False
description,Key Features of Alisha Solid Women's Cycling S...,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,Key Features of AW Bellies Sandals Wedges Heel...,Key Features of Alisha Solid Women's Cycling S...,Specifications of Sicons All Purpose Arnica Do...
product_rating,No rating available,No rating available,No rating available,No rating available,No rating available
overall_rating,No rating available,No rating available,No rating available,No rating available,No rating available
brand,Alisha,FabHomeDecor,AW,Alisha,Sicons
product_specifications,"{""product_specification""=>[{""key""=>""Number of ...","{""product_specification""=>[{""key""=>""Installati...","{""product_specification""=>[{""key""=>""Ideal For""...","{""product_specification""=>[{""key""=>""Number of ...","{""product_specification""=>[{""key""=>""Pet Type"",..."

In [ ]:
combined_data.describe(include='O').T

,count,unique,top,freq
uniq_id,40000,20000,c2d766ca982eca8304150849735ffef9,2
crawl_timestamp,40000,371,2015-12-01 12:40:44 +0000,3958
product_url,40000,20000,http://www.flipkart.com/alisha-solid-women-s-c...,2
product_name,40000,14784,S4S Stylish Women's Push-up Bra,188
product_category_tree,40000,6487,"[""Jewellery >> Necklaces & Chains >> Necklaces""]",3134
pid,40000,19998,JEAEGE8Q8GXYFTGU,4
image,39994,18589,"[""http://img6a.flixcart.com/image/car-mat/m/t/...",90
description,39996,18217,TheLostPuppy Back Cover for Apple iPad Air (Mu...,184
product_rating,40000,36,No rating available,36302
overall_rating,40000,36,No rating available,36302
brand,28272,3501,Allure Auto,938
product_specifications,39972,19087,"{""product_specification""=>[{""key""=>""Type"", ""va...",142

Observations
*  Combined data have exactly 2 products with same uniq_id
*  Same goes for product_url

In [ ]:
## removing missing values

df_fk.dropna(inplace=True)
df_fk.drop_duplicates(subset=['product_name','uniq_id'],inplace=True)
df_amz.dropna(inplace=True)
df_amz.drop_duplicates(subset=['product_name','uniq_id'],inplace=True)

## Recommendation System


* Model 1 : Works by removing duplicates having same **`product_name`** and **`uniq_id`**
* Model 2 : Works by removing duplicates having the same **`product_name`** only

### Model 1

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
## creating a function for creating combined data
def dataset(name):
  data = pd.concat([df_fk[df_fk['product_name']==name],df_amz])
  data.dropna(inplace=True)
  data.drop_duplicates(subset=['product_name','uniq_id'],inplace=True)
  return data

In [ ]:
## writng a funtion for recommendation

def recommendation(product_name):

  # checking the product name is valid or not
  if product_name not in df_fk['product_name'].to_list():
    print('Product not found!!!!\nEnter a Valid Product Name')

  else:
    data = dataset(product_name)

    #converting text into sparse matrix
    tfidf = TfidfVectorizer(max_features=50000,stop_words='english')
    x = tfidf.fit_transform(data['description'].values.astype('U'))

    # product for which we are getting recommendation
    query = x[0]


    scores = cosine_similarity(query,x)
    scores = scores.flatten()

    ## recommended indexes
    recommended_index = (-scores).argsort()[len(df_fk[df_fk['product_name']==product_name]):
                                            len(df_fk[df_fk['product_name']==product_name])+len(df_fk[df_fk['product_name']==product_name])]

    

    amazon_name = data.iloc[recommended_index]['product_name'].to_list()
    amazon_retail = data.iloc[recommended_index]['retail_price'].to_list()
    amazon_discount = data.iloc[recommended_index]['discounted_price'].to_list()

    ## constructing dataframe for recommended products 
    dict1 = {'Product name in Flipkart':product_name,
            'Retail Price in Flipkart':df_fk[df_fk['product_name']==product_name]['retail_price'],
            'Discounted Price in Flipkart':df_fk[df_fk['product_name']==product_name]['discounted_price'],
            'Product name in Amazon':amazon_name,
            'Retail Price in Amazon':amazon_retail,
            'Discounted Price in Amazon':amazon_discount}


    recommended_data = pd.DataFrame(dict1)
    return recommended_data

In [ ]:
recommendation('FabHomeDecor Fabric Double Sofa Bed')

,Product name in Flipkart,Retail Price in Flipkart,Discounted Price in Flipkart,Product name in Amazon,Retail Price in Amazon,Discounted Price in Amazon
1,FabHomeDecor Fabric Double Sofa Bed,32157.0,22646.0,COMFORT COUCH ENGINEERED WOOD 3 SEATER SOFA,28615.0,21455.0
7,FabHomeDecor Fabric Double Sofa Bed,32157.0,22646.0,@HOME ANNULUS SOLID WOOD DRESSING TABLE,22882.0,22208.0
16,FabHomeDecor Fabric Double Sofa Bed,32157.0,22646.0,ETHNIC HANDICRAFTS SOLID WOOD SINGLE BED,36983.0,31745.0
19,FabHomeDecor Fabric Double Sofa Bed,32157.0,22646.0,ETHNIC HANDICRAFTS SOLID WOOD QUEEN BED,39984.0,30653.0

In [ ]:
recommendation('Sicons All Purpose Arnica Dog Shampoo')

,Product name in Flipkart,Retail Price in Flipkart,Discounted Price in Flipkart,Product name in Amazon,Retail Price in Amazon,Discounted Price in Amazon
4,Sicons All Purpose Arnica Dog Shampoo,220.0,210.0,Sicons All Purpose Tea Tree Dog Shampoo,-11.0,0.0

In [ ]:
recommendation("Alisha Solid Women's Cycling Shorts")

,Product name in Flipkart,Retail Price in Flipkart,Discounted Price in Flipkart,Product name in Amazon,Retail Price in Amazon,Discounted Price in Amazon
0,Alisha Solid Women's Cycling Shorts,999.0,379.0,"Mynte Solid Women's Cycling Shorts, Gym Shorts...",1496.0,764.0
3,Alisha Solid Women's Cycling Shorts,699.0,267.0,"Mynte Solid Women's Cycling Shorts, Gym Shorts...",1479.0,838.0
6,Alisha Solid Women's Cycling Shorts,1199.0,479.0,"Mynte Solid Women's Cycling Shorts, Gym Shorts...",2494.0,1098.0
9,Alisha Solid Women's Cycling Shorts,1199.0,479.0,"Mynte Solid Women's Cycling Shorts, Gym Shorts...",1496.0,721.0
13,Alisha Solid Women's Cycling Shorts,999.0,379.0,"Mynte Solid Women's Cycling Shorts, Gym Shorts...",1497.0,720.0
15,Alisha Solid Women's Cycling Shorts,999.0,379.0,"Mynte Solid Women's Cycling Shorts, Gym Shorts...",1489.0,748.0

###Model 2

In [ ]:
## loading dataset
df_amz = pd.read_csv('/content/drive/MyDrive/data/Shack_Labs_Assignment/DS - Assignment Part 2 data set/amz_com-ecommerce_sample.csv',engine='python',encoding='latin1')
df_fk = pd.read_csv('/content/drive/MyDrive/data/Shack_Labs_Assignment/DS - Assignment Part 2 data set/flipkart_com-ecommerce_sample.csv')

In [ ]:
## removing missing values

df_fk.dropna(inplace=True)
df_fk.drop_duplicates(subset=['product_name'],inplace=True)
df_amz.dropna(inplace=True)
df_amz.drop_duplicates(subset=['product_name'],inplace=True)

In [ ]:
## creating a function for creating combined data
def dataset(name):
  data = pd.concat([df_fk[df_fk['product_name']==name],df_amz])
  data.dropna(inplace=True)
  data.drop_duplicates(subset=['product_name'],inplace=True)
  return data

In [ ]:
## writng a funtion for recommendation

def recommendation(product_name):

  # checking the product name is valid or not
  if product_name not in df_fk['product_name'].to_list():
    print('Product not found!!!!\nEnter a Valid Product Name')

  else:
    data = dataset(product_name)

    #converting text into sparse matrix
    tfidf = TfidfVectorizer(max_features=50000,stop_words='english')
    x = tfidf.fit_transform(data['description'].values.astype('U'))

    # product for which we are getting recommendation
    query = x[0]


    scores = cosine_similarity(query,x)
    scores = scores.flatten()

    ## recommended indexes
    recommended_index = (-scores).argsort()[len(df_fk[df_fk['product_name']==product_name]):
                                            len(df_fk[df_fk['product_name']==product_name])+len(df_fk[df_fk['product_name']==product_name])]

    

    amazon_name = data.iloc[recommended_index]['product_name'].to_list()
    amazon_retail = data.iloc[recommended_index]['retail_price'].to_list()
    amazon_discount = data.iloc[recommended_index]['discounted_price'].to_list()

    ## constructing dataframe for recommended products
    dict1 = {'Product name in Flipkart':product_name,
            'Retail Price in Flipkart':df_fk[df_fk['product_name']==product_name]['retail_price'],
            'Discounted Price in Flipkart':df_fk[df_fk['product_name']==product_name]['discounted_price'],
            'Product name in Amazon':amazon_name,
            'Retail Price in Amazon':amazon_retail,
            'Discounted Price in Amazon':amazon_discount}


    recommended_data = pd.DataFrame(dict1)
    return recommended_data

In [ ]:
recommendation('FabHomeDecor Fabric Double Sofa Bed')

,Product name in Flipkart,Retail Price in Flipkart,Discounted Price in Flipkart,Product name in Amazon,Retail Price in Amazon,Discounted Price in Amazon
1,FabHomeDecor Fabric Double Sofa Bed,32157.0,22646.0,COMFORT COUCH ENGINEERED WOOD 3 SEATER SOFA,28615.0,21455.0

In [ ]:
recommendation('Sicons All Purpose Arnica Dog Shampoo')

,Product name in Flipkart,Retail Price in Flipkart,Discounted Price in Flipkart,Product name in Amazon,Retail Price in Amazon,Discounted Price in Amazon
4,Sicons All Purpose Arnica Dog Shampoo,220.0,210.0,Sicons All Purpose Tea Tree Dog Shampoo,-11.0,0.0

In [ ]:
recommendation("Alisha Solid Women's Cycling Shorts")

,Product name in Flipkart,Retail Price in Flipkart,Discounted Price in Flipkart,Product name in Amazon,Retail Price in Amazon,Discounted Price in Amazon
0,Alisha Solid Women's Cycling Shorts,999.0,379.0,"Mynte Solid Women's Cycling Shorts, Gym Shorts...",1489.0,748.0